### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by yelm-212** [yelm-212/Todo#1]
# Minimum Requirements

## Todos for implementation

- [x] Mininum requirements
    - [x] Create to-do lists
    - [x] Read all to-do lists
    - [x] Read specific to-do content
    - [x] Update to-do content as completed
    - [x] Delete All todos
    - [x] Delete specific to-do content

## Expected task hours

3h
